#!/usr/bin/env bash
# ─── Toggle Claude Code between direct Bedrock and LiteLLM proxy ─────
#
# Creates a launcher at ~/.local/bin/claude-litellm that exports the
# right env vars and launches claude. No source needed.
#
# Usage:
#   ./scripts/services/claude-mode.sh litellm   # Set up LiteLLM mode
#   ./scripts/services/claude-mode.sh bedrock    # Set up Bedrock mode
#   ./scripts/services/claude-mode.sh status     # Show current mode
#
# Then launch:
#   claude-litellm    # Through LiteLLM (cost tracking, prompt logging)
#   claude            # Direct Bedrock (uses shell env vars)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WRAPPER="$HOME/.local/bin/claude-litellm"

show_status() {
    echo ""
    if [ -f "$WRAPPER" ]; then
        echo "  claude-litellm: INSTALLED ($WRAPPER)"
        echo "  Gateway: $(grep 'ANTHROPIC_BASE_URL=' "$WRAPPER" 2>/dev/null | head -1 | sed 's/.*=//')"
        echo "  Model:   $(grep 'ANTHROPIC_MODEL=' "$WRAPPER" 2>/dev/null | head -1 | sed 's/.*=//')"
        echo "  Fast:    $(grep 'ANTHROPIC_SMALL_FAST_MODEL=' "$WRAPPER" 2>/dev/null | head -1 | sed 's/.*=//')"
    else
        echo "  claude-litellm: NOT INSTALLED"
        echo "  Run: $0 litellm"
    fi
    echo ""
    echo "  claude (direct):  uses shell env (CLAUDE_CODE_USE_BEDROCK=$CLAUDE_CODE_USE_BEDROCK)"
    echo ""
}

write_litellm() {
    # Read master key
    local master_key=""
    local env_file="${REPO_ROOT}/.env.docker.local"
    if [ -f "$env_file" ]; then
        master_key=$(grep "^LITELLM_MASTER_KEY=" "$env_file" 2>/dev/null | cut -d= -f2-)
    fi
    master_key="${master_key:-sk-litellm-changeme}"

    # Check if LiteLLM is running
    if ! curl -sf http://localhost:8000/health/readiness &>/dev/null; then
        echo "WARNING: LiteLLM not running at http://localhost:8000"
        echo "  Start it: ./scripts/services/start-services.sh"
        echo ""
    fi

    # Create self-contained launcher
    mkdir -p "$(dirname "$WRAPPER")"
    cat > "$WRAPPER" << EOF
#!/usr/bin/env bash
# Launch Claude Code through LiteLLM proxy.
# Generated by claude-mode.sh — all env vars are self-contained.

# Strip any Bedrock config from shell
unset CLAUDE_CODE_USE_BEDROCK
unset ANTHROPIC_DEFAULT_HAIKU_MODEL
unset ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION

# Set LiteLLM proxy config
export ANTHROPIC_BASE_URL=http://localhost:8000
export ANTHROPIC_API_KEY=${master_key}
export ANTHROPIC_MODEL=claude-sonnet-4-6
export ANTHROPIC_SMALL_FAST_MODEL=claude-haiku-4-5
export CLAUDE_CODE_SKIP_AUTH_LOGIN=true
export CLAUDE_CODE_MAX_OUTPUT_TOKENS=4096

exec claude "\$@"
EOF
    chmod +x "$WRAPPER"

    echo "Installed: $WRAPPER"
    echo ""
    echo "  claude-litellm     → LiteLLM proxy (prompt logging, cost tracking)"
    echo "  claude             → Bedrock direct (shell env vars)"
    echo ""
    echo "Models routed through LiteLLM:"
    echo "  claude-sonnet-4-6  → Bedrock Sonnet (us-west-2)"
    echo "  claude-haiku-4-5   → Bedrock Haiku (us-west-2)"
    echo "  claude-opus-4-6    → Bedrock Opus (us-east-1)"
}

# ─── Main ─────────────────────────────────────────────────────────────

case "${1:-status}" in
    litellm|proxy)
        write_litellm
        ;;
    bedrock|direct)
        if [ -f "$WRAPPER" ]; then
            rm "$WRAPPER"
            echo "Removed $WRAPPER"
        fi
        echo "Use 'claude' directly (Bedrock via shell env vars)."
        ;;
    status|"")
        echo "Claude Code modes:"
        show_status
        ;;
    *)
        echo "Unknown mode: $1"
        echo "Usage: $0 {litellm|bedrock|status}"
        exit 1
        ;;
esac
